# Site settings
name: "Depart"
title: "Depart • A departure time calculator"
description: "Use Depart to help you plan when to leave for your flight, train, meeting, or any other type of appointment."

url: "http://depart.joelglovier.com"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed